"""
SEO content auto-fixer.

Takes an AuditReport from src.seo.audit, identifies LandingPage-backed
pages with fixable SEO issues and corrects them using web search for
current context + the premium LLM model.

Covered issues (auto-fixable on LandingPage rows):
  - Missing H1
  - Thin content (< 200 words)
  - Title too long (> 70 chars) or too short (< 20 chars)
  - Missing meta description (empty summary)
  - Heading hierarchy skips (e.g. H2 → H4)
  - Low inbound internal links (adds contextual links from related pages)

Not auto-fixable (require template or architectural changes):
  - Missing canonical / og:title / og:image — these are derived from
    page.canonical_path and page.title at render time; canonical is
    always set, og:title mirrors page.title (fixed via title fix),
    og:image is a static site-wide asset.
  - Missing JSON-LD — always generated by page_renderer.py for
    LandingPages; if audit detects it missing, it's a template bug.
  - Cluster nav missing — requires template include changes.

Only operates on LandingPage rows (sectors, explainers, pillar pages).
Tool pages and hub pages are excluded — their content is interactive or
index-style, and thin content is by design.

Usage (programmatic, called from run_daily.py Phase 6b):
    from src.seo.audit import run_audit
    from src.seo.content_fixer import fix_content_issues
    report = run_audit()
    result = fix_content_issues(report)
"""
from __future__ import annotations

import json
import logging
import re
from datetime import datetime

import httpx
from openai import OpenAI

from src.config import settings
from src.models import LandingPage, SessionLocal, init_db
from src.seo.audit import AuditReport

logger = logging.getLogger(__name__)

_MAX_FIXES_PER_RUN = 5

_ANY_TAG_RE = re.compile(r"<[^>]+>")
_ALLOWED_TAGS_RE = re.compile(
    r"<\s*/?\s*(h1|h2|h3|h4|p|ul|ol|li|strong|em|b|i|blockquote|a|table|thead|tbody|tr|th|td)(\s+[^>]*)?\s*/?\s*>",
    re.IGNORECASE,
)


def _sanitize_body_html(html: str) -> str:
    if not html:
        return ""

    def _replace(match: re.Match) -> str:
        if _ALLOWED_TAGS_RE.fullmatch(match.group(0)):
            return match.group(0)
        return ""

    return _ANY_TAG_RE.sub(_replace, html)


def _count_words(html: str) -> int:
    text = _ANY_TAG_RE.sub(" ", html or "")
    return len([w for w in text.split() if w])


def _web_search(query: str, *, max_results: int = 5) -> list[dict]:
    """Lightweight web search via DuckDuckGo HTML. Returns a list of
    {title, snippet, url} dicts. Best-effort — returns [] on failure."""
    try:
        resp = httpx.get(
            "https://html.duckduckgo.com/html/",
            params={"q": query},
            headers={"User-Agent": "CaracasResearch-SEOFixer/1.0"},
            timeout=10,
            follow_redirects=True,
        )
        if resp.status_code != 200:
            logger.warning("web_search: DDG returned %d for %r", resp.status_code, query)
            return []

        results: list[dict] = []
        html = resp.text

        for m in re.finditer(
            r'class="result__a"[^>]*href="([^"]*)"[^>]*>(.*?)</a>.*?'
            r'class="result__snippet"[^>]*>(.*?)</(?:a|td|div)',
            html,
            re.DOTALL,
        ):
            url = m.group(1)
            title = re.sub(r"<[^>]+>", "", m.group(2)).strip()
            snippet = re.sub(r"<[^>]+>", "", m.group(3)).strip()
            if title and snippet:
                results.append({"title": title, "snippet": snippet, "url": url})
                if len(results) >= max_results:
                    break

        return results
    except Exception as exc:
        logger.warning("web_search failed for %r: %s", query, exc)
        return []


def _premium_call(client: OpenAI, *, system: str, user: str, max_tokens: int = 3000) -> tuple[str, dict]:
    """Single premium-model call. Returns (raw_json_string, usage_dict)."""
    model = settings.openai_premium_model
    is_gpt5 = model.startswith("gpt-5") or model.startswith("o1") or model.startswith("o3")

    base_kwargs = dict(
        model=model,
        messages=[
            {"role": "system", "content": system},
            {"role": "user", "content": user},
        ],
        response_format={"type": "json_object"},
    )

    if is_gpt5:
        base_kwargs["max_completion_tokens"] = max_tokens
    else:
        base_kwargs["max_tokens"] = max_tokens
        base_kwargs["temperature"] = 0.4

    response = client.chat.completions.create(**base_kwargs)
    raw = response.choices[0].message.content
    usage = getattr(response, "usage", None)
    in_tok = getattr(usage, "prompt_tokens", 0) if usage else 0
    out_tok = getattr(usage, "completion_tokens", 0) if usage else 0
    cost = (
        (in_tok or 0) / 1_000_000 * settings.llm_premium_input_price_per_mtok
        + (out_tok or 0) / 1_000_000 * settings.llm_premium_output_price_per_mtok
    )
    return raw, {
        "input_tokens": in_tok,
        "output_tokens": out_tok,
        "cost_usd": round(cost, 4),
        "model": model,
    }


_SYSTEM_PROMPT = """You are a senior emerging-markets analyst at Caracas Research. You are fixing SEO issues on existing landing pages. Your writing is:
- Concise, authoritative, and backed by the web search results provided
- Plain English, no jargon clichés, no filler
- Structured with HTML tags: h1, h2, h3, p, ul, ol, li, strong, em, a (with real href paths)
- Focused on Venezuela — sanctions (OFAC), investment, oil & gas, mining, trade, travel, or the specific topic of the page

You MUST return a single JSON object. The exact fields depend on the task described in the user prompt."""


def _fix_missing_h1(
    client: OpenAI,
    page: LandingPage,
    search_results: list[dict],
) -> dict | None:
    """Generate an H1 for a page that's missing one."""
    search_ctx = "\n".join(
        f"- {r['title']}: {r['snippet']}" for r in search_results
    ) or "No search results available."

    user_prompt = f"""This page needs an H1 heading. Generate one based on the page context and current web search results.

PAGE TITLE: {page.title}
PAGE SUMMARY: {page.summary or '(none)'}
PAGE PATH: {page.canonical_path}
PAGE TYPE: {page.page_type}

CURRENT WEB SEARCH RESULTS for this topic:
{search_ctx}

Return JSON with:
- h1 (string, 40-80 chars, keyword-rich, descriptive, matches the page's topic)
- body_prefix (string, 1-2 HTML paragraphs with <h1> and a strong opening <p> to prepend to the existing body)"""

    try:
        raw, usage = _premium_call(client, system=_SYSTEM_PROMPT, user=user_prompt, max_tokens=500)
        data = json.loads(raw)
        return {
            "h1": data.get("h1", ""),
            "body_prefix": _sanitize_body_html(data.get("body_prefix", "")),
            "usage": usage,
        }
    except Exception as exc:
        logger.warning("fix_missing_h1 failed for %s: %s", page.canonical_path, exc)
        return None


def _fix_thin_content(
    client: OpenAI,
    page: LandingPage,
    current_word_count: int,
    search_results: list[dict],
) -> dict | None:
    """Expand a page with thin content to 400+ words using web search context."""
    search_ctx = "\n".join(
        f"- {r['title']}: {r['snippet']}" for r in search_results
    ) or "No search results available."

    current_body_preview = (page.body_html or "")[:2000]

    user_prompt = f"""This page has thin content ({current_word_count} words). Expand it to 400-600 words using the current web search results as grounding.

PAGE TITLE: {page.title}
PAGE SUMMARY: {page.summary or '(none)'}
PAGE PATH: {page.canonical_path}
PAGE TYPE: {page.page_type}
CURRENT WORD COUNT: {current_word_count}

CURRENT BODY (first 2000 chars):
{current_body_preview}

CURRENT WEB SEARCH RESULTS for this topic:
{search_ctx}

Return JSON with:
- body_html (string, the COMPLETE expanded body — keep existing good content, add new sections/paragraphs grounded in the search results. Use h2, h3, p, ul, li, strong, em, a tags. Target 400-600 words.)
- word_count (integer, the word count of the new body)"""

    try:
        raw, usage = _premium_call(client, system=_SYSTEM_PROMPT, user=user_prompt, max_tokens=3000)
        data = json.loads(raw)
        body = _sanitize_body_html(data.get("body_html", ""))
        wc = _count_words(body)
        if wc < current_word_count:
            logger.warning(
                "fix_thin_content for %s produced fewer words (%d vs %d); skipping",
                page.canonical_path, wc, current_word_count,
            )
            return None
        return {
            "body_html": body,
            "word_count": wc,
            "usage": usage,
        }
    except Exception as exc:
        logger.warning("fix_thin_content failed for %s: %s", page.canonical_path, exc)
        return None


def _fix_title(
    client: OpenAI,
    page: LandingPage,
    current_title: str,
    issue: str,  # "too_long" or "too_short"
    search_results: list[dict],
) -> dict | None:
    """Generate a better title that's 30-65 chars, keyword-rich."""
    search_ctx = "\n".join(
        f"- {r['title']}: {r['snippet']}" for r in search_results
    ) or "No search results available."

    user_prompt = f"""This page's title is {issue.replace('_', ' ')} ({len(current_title)} chars). Generate a better SEO title.

CURRENT TITLE: {current_title}
PAGE PATH: {page.canonical_path}
PAGE TYPE: {page.page_type}
PAGE SUMMARY: {page.summary or '(none)'}

CURRENT WEB SEARCH RESULTS for this topic:
{search_ctx}

Return JSON with:
- title (string, 30-65 chars, keyword-rich, descriptive, includes "Venezuela" if relevant)
- rationale (string, 1 sentence explaining why this title is better)"""

    try:
        raw, usage = _premium_call(client, system=_SYSTEM_PROMPT, user=user_prompt, max_tokens=300)
        data = json.loads(raw)
        new_title = data.get("title", "").strip()
        if not new_title or len(new_title) > 70 or len(new_title) < 15:
            return None
        return {"title": new_title, "usage": usage}
    except Exception as exc:
        logger.warning("fix_title failed for %s: %s", page.canonical_path, exc)
        return None


def _fix_missing_description(
    client: OpenAI,
    page: LandingPage,
    search_results: list[dict],
) -> dict | None:
    """Generate a meta description (summary) for a page that's missing one."""
    search_ctx = "\n".join(
        f"- {r['title']}: {r['snippet']}" for r in search_results
    ) or "No search results available."

    body_preview = (page.body_html or "")[:1500]

    user_prompt = f"""This page is missing a meta description. Generate one based on the page content and search results.

PAGE TITLE: {page.title}
PAGE PATH: {page.canonical_path}
PAGE TYPE: {page.page_type}

CURRENT BODY (first 1500 chars):
{body_preview}

CURRENT WEB SEARCH RESULTS for this topic:
{search_ctx}

Return JSON with:
- description (string, 120-155 chars, compelling, includes primary keyword, describes the page's value proposition)"""

    try:
        raw, usage = _premium_call(client, system=_SYSTEM_PROMPT, user=user_prompt, max_tokens=300)
        data = json.loads(raw)
        desc = data.get("description", "").strip()
        if not desc or len(desc) < 50:
            return None
        return {"description": desc, "usage": usage}
    except Exception as exc:
        logger.warning("fix_missing_description failed for %s: %s", page.canonical_path, exc)
        return None


_HEADING_RE = re.compile(r"<h([1-6])(\s[^>]*)?>", re.IGNORECASE)


def _fix_heading_hierarchy(page: LandingPage) -> dict | None:
    """Fix heading hierarchy skips by demoting/promoting headings to
    eliminate gaps. Pure regex pass — no LLM call needed."""
    if not page.body_html:
        return None

    levels_found: list[tuple[int, int]] = []  # (position, level)
    for m in _HEADING_RE.finditer(page.body_html):
        levels_found.append((m.start(), int(m.group(1))))

    if len(levels_found) < 2:
        return None

    has_skip = False
    for i in range(1, len(levels_found)):
        prev_level = levels_found[i - 1][1]
        curr_level = levels_found[i][1]
        if curr_level > prev_level + 1:
            has_skip = True
            break

    if not has_skip:
        return None

    remap: dict[int, int] = {}
    max_allowed = 1
    for _pos, level in levels_found:
        if level <= max_allowed:
            remap.setdefault(level, level)
            max_allowed = level + 1
        else:
            target = min(level, max_allowed)
            remap[level] = target
            max_allowed = target + 1

    if all(k == v for k, v in remap.items()):
        return None

    new_html = page.body_html

    for old_level in sorted(remap.keys(), reverse=True):
        new_level = remap[old_level]
        if old_level == new_level:
            continue
        new_html = re.sub(
            rf"<h{old_level}(\s[^>]*)?>",
            lambda m: f"<h{new_level}{m.group(1) or ''}>",
            new_html,
        )
        new_html = re.sub(
            rf"</h{old_level}>",
            f"</h{new_level}>",
            new_html,
        )

    if new_html == page.body_html:
        return None

    return {"body_html": new_html}


def _fix_inbound_links(
    client: OpenAI,
    target_page: LandingPage,
    source_pages: list[LandingPage],
    search_results: list[dict],
) -> list[dict] | None:
    """Add a contextual internal link to `target_page` from up to 2
    related source pages. Returns list of {page_id, new_body_html} dicts."""
    if not source_pages:
        return None

    search_ctx = "\n".join(
        f"- {r['title']}: {r['snippet']}" for r in search_results
    ) or "No search results available."

    sources_desc = "\n".join(
        f"- [{s.page_key}] title=\"{s.title}\", path={s.canonical_path}, "
        f"body_preview=\"{(s.body_html or '')[:300]}...\""
        for s in source_pages[:3]
    )

    user_prompt = f"""Add a contextual internal link to a target page from source pages.

TARGET PAGE:
- Title: {target_page.title}
- Path: {target_page.canonical_path}
- Summary: {target_page.summary or '(none)'}

SOURCE PAGES (add a link FROM one of these TO the target):
{sources_desc}

CURRENT WEB SEARCH RESULTS for the target topic:
{search_ctx}

For each source page where a link makes sense, return how to insert it.
Return JSON with:
- links (array of objects, each with):
  - source_page_key (string, the page_key of the source)
  - anchor_text (string, 3-8 words, descriptive of target)
  - insert_after_snippet (string, ~50-80 chars of existing text in the source body AFTER which the link sentence should be inserted)
  - link_sentence (string, a natural 1-sentence paragraph containing an <a href="{{target_path}}">{{anchor_text}}</a> link)

Only add links where they are topically relevant. Max 2 links."""

    try:
        raw, usage = _premium_call(client, system=_SYSTEM_PROMPT, user=user_prompt, max_tokens=800)
        data = json.loads(raw)
        links = data.get("links", [])
        if not links:
            return None

        results = []
        for link_info in links[:2]:
            source_key = link_info.get("source_page_key", "")
            snippet = link_info.get("insert_after_snippet", "")
            sentence = _sanitize_body_html(link_info.get("link_sentence", ""))

            if not source_key or not snippet or not sentence:
                continue

            source = next((s for s in source_pages if s.page_key == source_key), None)
            if not source or not source.body_html:
                continue

            if snippet in source.body_html:
                new_body = source.body_html.replace(
                    snippet, snippet + f"\n<p>{sentence}</p>", 1
                )
                results.append({
                    "page_id": source.id,
                    "page_key": source_key,
                    "new_body_html": new_body,
                    "anchor_text": link_info.get("anchor_text", ""),
                })

        return results if results else None
    except Exception as exc:
        logger.warning("fix_inbound_links failed for %s: %s", target_page.canonical_path, exc)
        return None


def _find_landing_page(db, path: str) -> LandingPage | None:
    """Look up a LandingPage by its canonical_path."""
    norm = "/" + path.lstrip("/").rstrip("/")
    return (
        db.query(LandingPage)
        .filter(LandingPage.canonical_path == norm)
        .first()
    )


def fix_content_issues(
    report: AuditReport,
    *,
    max_fixes: int = _MAX_FIXES_PER_RUN,
) -> dict:
    """Scan the audit report for fixable issues on LandingPage-backed
    pages and apply LLM-generated fixes.

    Handles: missing H1, thin content, title too long/short, missing
    meta description, heading hierarchy skips, and low inbound links.

    Returns a summary dict for the pipeline log."""
    if not settings.openai_api_key:
        return {"status": "skipped", "reason": "no OpenAI API key"}

    missing_h1_paths: list[str] = []
    thin_content_paths: list[tuple[str, int]] = []  # (path, word_count)
    bad_title_paths: list[tuple[str, str]] = []  # (path, "too_long"|"too_short")
    missing_desc_paths: list[str] = []
    heading_skip_paths: list[str] = []
    low_inbound_paths: list[str] = []

    for pa_key, pa in report.page_audits.items():
        if pa.status_code != 200:
            continue
        for f in pa.findings:
            if f.severity.value == "error" and f.category == "h1" and "No H1" in f.message:
                missing_h1_paths.append(pa.path)
            if f.category == "thin_content" and "Thin content" in f.message:
                thin_content_paths.append((pa.path, pa.body_word_count))
            if f.category == "title" and "too short" in f.message:
                bad_title_paths.append((pa.path, "too_short"))
            if f.category == "title" and "too long" in f.message:
                bad_title_paths.append((pa.path, "too_long"))
            if f.category == "meta_description" and "Missing" in f.message:
                missing_desc_paths.append(pa.path)
            if f.category == "heading_hierarchy" and "Skipped" in f.message:
                heading_skip_paths.append(pa.path)

    for f in report.findings:
        if f.category == "orphan_hub" and "inbound" in f.message:
            low_inbound_paths.append(f.path)

    all_issues = (
        missing_h1_paths + [p for p, _ in thin_content_paths]
        + [p for p, _ in bad_title_paths] + missing_desc_paths
        + heading_skip_paths + low_inbound_paths
    )
    if not all_issues:
        return {"status": "ok", "fixed": 0, "reason": "no fixable issues"}

    init_db()
    db = SessionLocal()
    client = OpenAI(api_key=settings.openai_api_key)

    fixed = 0
    skipped = 0
    total_cost = 0.0
    details: list[dict] = []

    try:
        # --- Fix missing H1 ---
        for path in missing_h1_paths:
            if fixed >= max_fixes:
                break

            page = _find_landing_page(db, path)
            if page is None:
                skipped += 1
                continue

            search_query = f"Venezuela {page.title or page.page_key} 2026"
            search_results = _web_search(search_query)

            result = _fix_missing_h1(client, page, search_results)
            if result is None:
                skipped += 1
                continue

            body_prefix = result["body_prefix"]
            if body_prefix and page.body_html:
                page.body_html = body_prefix + "\n" + page.body_html
                page.word_count = _count_words(page.body_html)
            elif body_prefix:
                page.body_html = body_prefix
                page.word_count = _count_words(page.body_html)

            page.updated_at = datetime.utcnow()
            db.commit()

            cost = result["usage"]["cost_usd"]
            total_cost += cost
            fixed += 1
            details.append({
                "path": path,
                "fix": "missing_h1",
                "h1": result["h1"],
                "cost_usd": cost,
            })
            logger.info("Fixed missing H1 on %s: %r", path, result["h1"])

        # --- Fix thin content ---
        for path, word_count in thin_content_paths:
            if fixed >= max_fixes:
                break

            page = _find_landing_page(db, path)
            if page is None:
                skipped += 1
                continue

            if word_count >= 200:
                skipped += 1
                continue

            search_query = f"Venezuela {page.title or page.page_key} latest 2026"
            search_results = _web_search(search_query)

            result = _fix_thin_content(client, page, word_count, search_results)
            if result is None:
                skipped += 1
                continue

            page.body_html = result["body_html"]
            page.word_count = result["word_count"]
            page.updated_at = datetime.utcnow()
            db.commit()

            cost = result["usage"]["cost_usd"]
            total_cost += cost
            fixed += 1
            details.append({
                "path": path,
                "fix": "thin_content",
                "old_words": word_count,
                "new_words": result["word_count"],
                "cost_usd": cost,
            })
            logger.info(
                "Fixed thin content on %s: %d -> %d words",
                path, word_count, result["word_count"],
            )

        # --- Fix title too long/short ---
        for path, issue in bad_title_paths:
            if fixed >= max_fixes:
                break

            page = _find_landing_page(db, path)
            if page is None:
                skipped += 1
                continue

            search_query = f"Venezuela {page.page_key} 2026"
            search_results = _web_search(search_query)

            result = _fix_title(client, page, page.title or "", issue, search_results)
            if result is None:
                skipped += 1
                continue

            old_title = page.title
            page.title = result["title"]
            page.updated_at = datetime.utcnow()
            db.commit()

            cost = result["usage"]["cost_usd"]
            total_cost += cost
            fixed += 1
            details.append({
                "path": path,
                "fix": f"title_{issue}",
                "old_title": old_title,
                "new_title": result["title"],
                "cost_usd": cost,
            })
            logger.info("Fixed title (%s) on %s: %r -> %r", issue, path, old_title, result["title"])

        # --- Fix missing meta description ---
        for path in missing_desc_paths:
            if fixed >= max_fixes:
                break

            page = _find_landing_page(db, path)
            if page is None:
                skipped += 1
                continue

            if page.summary and len(page.summary.strip()) >= 50:
                skipped += 1
                continue

            search_query = f"Venezuela {page.title or page.page_key} 2026"
            search_results = _web_search(search_query)

            result = _fix_missing_description(client, page, search_results)
            if result is None:
                skipped += 1
                continue

            page.summary = result["description"]
            page.updated_at = datetime.utcnow()
            db.commit()

            cost = result["usage"]["cost_usd"]
            total_cost += cost
            fixed += 1
            details.append({
                "path": path,
                "fix": "missing_meta_description",
                "description": result["description"],
                "cost_usd": cost,
            })
            logger.info("Fixed missing meta description on %s", path)

        # --- Fix heading hierarchy skips (no LLM cost) ---
        for path in heading_skip_paths:
            if fixed >= max_fixes:
                break

            page = _find_landing_page(db, path)
            if page is None:
                skipped += 1
                continue

            result = _fix_heading_hierarchy(page)
            if result is None:
                skipped += 1
                continue

            page.body_html = result["body_html"]
            page.updated_at = datetime.utcnow()
            db.commit()

            fixed += 1
            details.append({
                "path": path,
                "fix": "heading_hierarchy",
                "cost_usd": 0.0,
            })
            logger.info("Fixed heading hierarchy on %s", path)

        # --- Fix low inbound links ---
        for path in low_inbound_paths:
            if fixed >= max_fixes:
                break

            target_page = _find_landing_page(db, path)
            if target_page is None:
                skipped += 1
                continue

            related_pages = (
                db.query(LandingPage)
                .filter(LandingPage.canonical_path != target_page.canonical_path)
                .filter(LandingPage.body_html.isnot(None))
                .order_by(LandingPage.last_generated_at.desc())
                .limit(5)
                .all()
            )
            if not related_pages:
                skipped += 1
                continue

            search_query = f"Venezuela {target_page.title or target_page.page_key} 2026"
            search_results = _web_search(search_query)

            link_results = _fix_inbound_links(client, target_page, related_pages, search_results)
            if not link_results:
                skipped += 1
                continue

            links_added = 0
            for lr in link_results:
                source = db.query(LandingPage).get(lr["page_id"])
                if source:
                    source.body_html = lr["new_body_html"]
                    source.updated_at = datetime.utcnow()
                    links_added += 1

            if links_added:
                db.commit()
                fixed += 1
                cost = 0.0  # cost tracked at the LLM call level
                details.append({
                    "path": path,
                    "fix": "low_inbound_links",
                    "links_added": links_added,
                    "sources": [lr["page_key"] for lr in link_results],
                    "cost_usd": cost,
                })
                logger.info("Added %d inbound link(s) to %s", links_added, path)
            else:
                skipped += 1

        return {
            "status": "ok",
            "fixed": fixed,
            "skipped": skipped,
            "total_cost_usd": round(total_cost, 4),
            "details": details,
        }
    except Exception as exc:
        logger.exception("content fixer failed: %s", exc)
        try:
            db.rollback()
        except Exception:
            pass
        return {"status": "error", "error": str(exc), "fixed": fixed}
    finally:
        db.close()
